AWSTemplateFormatVersion: "2010-09-09"
Description: Queue to process payment notifications
Parameters:
  IamStackName:
    Description: Name of an active CloudFormation stack that contains the IAM resources
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: ^[a-zA-Z][-a-zA-Z0-9]*$
Resources:
  StripeWebHookQueue:
    Type: AWS::SQS::Queue

  StripeWebHookQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Id: StripeWebHookQueuePolicy
        Statement:
          - Sid: Allow-WebProfile
            Effect: Allow
            Principal:
              AWS:
                Fn::ImportValue: !Sub '${IamStackName}:WebServerRoleArn'
            Action:
              - sqs:SendMessage
              - sqs:ReceiveMessage
              - sqs:DeleteMessage
            Resource: !GetAtt StripeWebHookQueue.Arn
      Queues:
        - !Ref StripeWebHookQueue

Outputs:
  StripeWebHookQueueURL:
    Description: Stripe WebHook Queue
    Value: !Ref StripeWebHookQueue
    Export:
      Name: !Join [ ':', [ !Ref 'AWS::StackName', 'StripeWebHookQueueURL' ] ]


